export const FIELD_CLASS = "h-10 px-4"
export const BUTTON_HEIGHT_CLASS = "h-10"
export const PASSWORD_FIELD_CLASS = "h-10 pl-4"
export const SELECT_TRIGGER_CLASS = "data-[size=default]:h-10 w-full px-4"
export const TEXTAREA_CLASS = "px-4 py-3"
